package message

var (
	RESULT_CODE_VERIFICATION_CODE_REQUEST_TOO_FREQUENT int32 = 100
	RESULT_CODE_VERIFICATION_CODE_TRY_FREQUENT         int32 = 102
	RESULT_CODE_VERIFICATION_CODE_REQUEST_ERROR        int32 = 103
	RESULT_CODE_VERIFICATION_CODE_ERROR                int32 = 104
	RESULT_CODE_VERIFICATION_CODE_EXPIRED              int32 = 105
)
