version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: "host"

  # Nginx Exporter (Basic Status)
  nginx-exporter:
    image: bitnami/nginx-exporter:latest
    container_name: nginx-exporter
    restart: always
    # 强制传参，覆盖默认行为
    command: ["-nginx.scrape-uri", "http://127.0.0.1:80/stub_status"]
    network_mode: "host"
    privileged: true

  # Nginx Log Exporter (Detailed Metrics)
  nginx-log-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.11.0
    container_name: nginx-log-exporter
    restart: always
    user: "0:0"
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      # 挂载 HCL 文件
      - ./nginx-log-exporter.hcl:/etc/prometheus-nginxlog-exporter.hcl
      - /etc/localtime:/etc/localtime:ro
    # 指定 HCL 配置文件路径
    command: ["-config-file", "/etc/prometheus-nginxlog-exporter.hcl"]
    ports:
      - "4040:4040"
    networks:
      - monitor-net
volumes:
  prometheus_data:
  grafana_data:

networks:
  monitor-net:
    driver: bridge