// Code generated by tool. DO NOT EDIT.
#ifndef RESULT_CODE_H
#define RESULT_CODE_H

const int RESULT_CODE_SUCCESS = 200; // 成功
const int RESULT_CODE_ERROR = 500; // 错误
const int RESULT_CODE_EXIST_SAME_NAME = 1001; // 存在相同昵称

#endif // RESULT_CODE_H